#!/bin/sh
if [[ "$(sudo docker images amovane/pwnkit:latest | grep pwnkit 2> /dev/null)" == "" ]]; then
  echo "Pwnkit is not installed yet. Please run pwnkit-update."
else
  clear
  MY_PATH=$(dirname "$0")
  "$MY_PATH/pwnkit-ascii"
  sudo docker run -d -t --rm --cap-add=SYS_PTRACE --security-opt seccomp=unconfined -v /Volumes/:/Volumes/ -v /etc/hosts:/etc/hosts_host:ro -e PWNKIT_PATH=`pwd` amovane/pwnkit:latest
fi
