#!/bin/sh
set -e
[ "$UID" -eq 0 ] || exec sudo sh "$0" "$@"

MY_PATH=$(dirname "$0")
"$MY_PATH/pwnkit-ascii"

# Check for docker

echo "Pulling latest base image . . ."
sudo docker pull kalilinux/kali-rolling:latest --platform linux/arm64
echo "Base image pulled."

echo "Building docker image . . ."
sudo docker build  --platform linux/arm64 -t amovane/pwnkit:latest --pull .
echo "Docker image built successfully."

echo "Pushing new version to registry . . ."
sudo docker push amovane/pwnkit:latest
echo "New image pushed succesfully!"
